>P1;4DOJ
, 729 bases : : : : : : : : :
 MTTSDPNPKP IVEDAQPEQI TATEELAGLL ENPTNLEGKL ADAEEEIILE
 GEDTQASLNW SVIVPALVIV LATVVWGIGF KDSFTNFASS ALSAVVDNLG
 WAFILFGTVF VFFIVVIAAS KFGTIRLGRI DEAPEFRTVS WISMMFAAGM
 GIGLMFYGTT EPLTFYRNGV PG--HDEHNV GVAMSTTMFH WTLHPWAIYA
 IVGLAIAYST FRVGRKQLLS SAFVPLIGEK GAEGWLGKLI DILAIIATVF
 GTACSLGLGA LQIGAGLSAA NIIEDPSDWT IVGIVSVLTL AFIFSAISGV
 GKGIQYLSNA NMVLAALLAI FVFVVGPTVS ILNLLPGSIG NYLSNFFQMA
 GRTAMSADGT AGEWLGSWTI FYWAWWISWS PFVGMFLARI SRGRSIREFI
 LGVLLVPAGV STVWFSIFGG TAIVFEQNGE SIWGD---GA AEEQLFGLLH
 ALPGGQIMGI IAMILLGTFF ITSADSASTV MGTMSQHGQL ---EANKWVT
 AAWGVATAAI GLTLLLSGGD NALSNLQNVT IVAATPFLFV VIGLMFALVK
 DLS------- ---------- ---NDVIYLE YREQQRFN-- -ARLARERRV
 HNEHRKRELA AKRRRERKA- ------SGAG KRR------- ----------
 ---------- ---------- ---------- ---------- ----------
 ---------- ---------- ---------*

>P1;BET
, 729 bases : : : : : : : : :
 ---------- ---------- ---------- ---------- -----MTDLS
 HSREKDKINP VVFYTSAGLI LLFSLTTILF RDFSALWIGR TLDWVSKTFG
 WYYLLAATLY IVFVVCIACS RFGSVKLGPE QSKPEFSLLS WAAMLFAAGI
 GIDLMFFSVA EPVTQYMQPP EGAGQTIEAA RQAMVWTLFH YGLTGWSMYA
 LMGMALGYFS YRYNLPLTIR SALYPIFGKR -INGPIGHSV DIAAVIGTIF
 GIATTLGIGV VQLNYGLSVL FDIPDS-MAA KAALIALSVI IATISVTSGV
 DKGIRVLSEL NVALALGLIL FVLFMGDTSF LLNALVLNVG DYVNRFMGMT
 LNSFAFDRPV --EWMNNWTL FFWAWWVAWS PFVGLFLARI SRGRTIRQFV
 LGTLIIPFTF TLLWLSVFGN SALYEIIHGG AAFAEEAMVH PERGFYSLLA
 QYPAFTFSAS VATITGLLFY VTSADSGALV LGNFTSQLKD INSDAPGWLR
 VFWSVAIGLL TLGMLMTNG- --ISALQNTT VIMGLPFSFV IFFVMAGLYK
 SLKVEDYRRE SANRDTAPRP LGLQDRLSWK KRLSRLMNYP GTRYTKQMME
 TVCYPAMEEV AQELRLRGAY VELKSLPPEE GQQLGHLDLL VHMGEEQNFV
 YQIWPQQYSV PGFTYRARSG KSTYYRLETF LLEGSQGNDL MDYSKEQVIT
 DILDQYERHL NFIHLHREAP GHSVMFPDA*

