>P1;BET
, 700 bases: : : : : : : : : 
 ---------- ------MTDL SHSREKDKIN PVVFYTSAGL ILLFSLTTIL
 FRDFSALWIG RTLDWVSKTF GWYYLLAATL YIVFVVCIAC SRFGSVKLGP
 EQSKPEFSLL SWAAMLFAAG IGIDLMFFSV AEPVTQYMQP PEGAGQTIEA
 ARQAMVWTLF HYGLTGWSMY ALMGMALGYF SYRYNLPLTI RSALYPIFGK
 R-INGPIGHS VDIAAVIGTI FGIATTLGIG VVQLNYGLSV LFDIPD-SMA
 AKAALIALSV IIATISVTSG VDKGIRVLSE LNVALALGLI LFVLFMGDTS
 FLLNALVLNV GDYVNRFMGM TLNSFAFDRP V--EWMNNWT LFFWAWWVAW
 SPFVGLFLAR ISRGRTIRQF VLGTLIIPFT FTLLWLSVFG NSALYEIIHG
 GAAFAEEAMV HPERGFYSLL AQYPAFTFSA SVATITGLLF YVTSADSGAL
 VLGNFTSQLK DINSDAPGWL RVFWSVAIGL LTLGMLMTNG ---ISALQNT
 TVIMGLPFSF VIFFVMAGLY KSLKVEDYRR ESANRDTAPR PLGLQDRLSW
 KKRLSRLMNY PGTRYTKQMM ETVCYPAMEE VAQELRLRGA YVELKSLPPE
 EGQQLGHLDL LVHMGEEQNF VYQIWPQQYS VPGFTYRARS GKSTYYRLET
 FLLEGSQGND LMDYSKEQVI TDILDQYERH LNFIHLHREA PGHSVMFPDA*

>P1;PDBID
, 700 bases: : : : : : : : : 
 LENPTNLEGK LADAEEEIIL EGEDTQASLN WSVIVPALVI VLATVVWGIG
 FKDSFTNFAS SALSAVVDNL GWAFILFGTV FVFFIVVIAA SKFGTIRLGR
 IDEAPEFRTV SWISMMFAAG MGIDLMFYGT TEPLTFYRNG VPG--HDEHN
 VGVAMSTTMF HWTLHPWAIY AIVGLAIAYS TFRVGRKQLL SSAFVPLIGE
 KGAEGWLGKL IDILAIIATV FGTACSLGLG ALQIGAGLSA ANIIEDPSDW
 TIVGIVSVLT LAFIFSAISG VGKGIQYLSN ANMVLAALLA IFVFVVGPTV
 SILNLLPGSI GNYLSNFFQM AGRTAMSADG TAGEWLGSWT IFYWAWWISW
 SPFVGMFLAR ISRGRSIREF ILGVLLVPAG VSTVWFSIFG GTAIVFEQNG
 ESIWGDGA-- -AEEQLFGLL HALPGGQIMG IIAMILLGTF FITSADSAST
 VMGTMSQHGQ L---EANKWV TAAWGVATAA IGLTLLLSGG DNALSNLQNV
 TIVAATPFLF VVIGLMFALV KDLSNDVIYL EYREQQRFNA RLARERRVHN
 EHRKRELAAK RRRE------ --------RK ASGAGKRR-- ----------
 ---------- ---------- ---------- ---------- ----------
 ---------- ---------- ---------- ---------- ----------*
