>P1;BET
, 729 bases
 ---------- ---------- ---------- ---------- -----MTDLS
 HSREKDKINP VVFYTSAGLI LLFSLTTILF RDFSALWIGR TLDWVSKTFG
 WYYLLAATLY IVFVVCIACS RFGSVKLGPE QSKPEFSLLS WAAMLFAAGI
 GIDLMFFSVA EPVTQYMQPP EGAGQTIEAA RQAMVWTLFH YGLTGWSMYA
 LMGMALGYFS YRYNLPLTIR SALYPIFGKR -INGPIGHSV DIAAVIGTIF
 GIATTLGIGV VQLNYGLSVL FDIPDS-MAA KAALIALSVI IATISVTSGV
 DKGIRVLSEL NVALALGLIL FVLFMGDTSF LLNALVLNVG DYVNRFMGMT
 LNSFAFDRPV --EWMNNWTL FFWAWWVAWS PFVGLFLARI SRGRTIRQFV
 LGTLIIPFTF TLLWLSVFGN SALYEIIHGG AAFAEEAMVH PERGFYSLLA
 QYPAFTFSAS VATITGLLFY VTSADSGALV LGNFTSQLKD INSDAPGWLR
 VFWSVAIGLL TLGMLMTNG- --ISALQNTT VIMGLPFSFV IFFVMAGLYK
 SLKVEDYRRE SANRDTAPRP LGLQDRLSWK KRLSRLMNYP GTRYTKQMME
 TVCYPAMEEV AQELRLRGAY VELKSLPPEE GQQLGHLDLL VHMGEEQNFV
 YQIWPQQYSV PGFTYRARSG KSTYYRLETF LLEGSQGNDL MDYSKEQVIT
 DILDQYERHL NFIHLHREAP GHSVMFPDA*

